import { useDispatch, useSelector } from 'react-redux';
import { updateForm, resetForm, logInteraction } from '../store/interactionSlice';

const s = {
  grid: {
    display: 'grid',
    gridTemplateColumns: '1fr 340px',
    gap: '20px',
    alignItems: 'start',
  },
  card: {
    background: '#fff',
    borderRadius: '12px',
    border: '1px solid #dadce0',
    overflow: 'hidden',
    boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
  },
  cardHeader: {
    padding: '16px 20px',
    borderBottom: '1px solid #f1f3f4',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  cardTitle: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#202124',
  },
  cardBody: { padding: '20px' },
  row: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
    marginBottom: '16px',
  },
  field: { marginBottom: '16px' },
  label: {
    display: 'block',
    fontSize: '12px',
    fontWeight: '500',
    color: '#5f6368',
    marginBottom: '6px',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  input: {
    width: '100%',
    padding: '9px 12px',
    border: '1px solid #dadce0',
    borderRadius: '8px',
    fontSize: '14px',
    color: '#202124',
    outline: 'none',
    transition: 'border-color 0.15s',
    background: '#fff',
  },
  textarea: {
    width: '100%',
    padding: '9px 12px',
    border: '1px solid #dadce0',
    borderRadius: '8px',
    fontSize: '14px',
    color: '#202124',
    outline: 'none',
    resize: 'vertical',
    minHeight: '80px',
    fontFamily: 'Inter, sans-serif',
    lineHeight: '1.5',
  },
  select: {
    width: '100%',
    padding: '9px 12px',
    border: '1px solid #dadce0',
    borderRadius: '8px',
    fontSize: '14px',
    color: '#202124',
    outline: 'none',
    background: '#fff',
  },
  sentimentGroup: {
    display: 'flex',
    gap: '8px',
  },
  sentimentBtn: (active, color) => ({
    flex: 1,
    padding: '8px',
    border: `2px solid ${active ? color : '#dadce0'}`,
    borderRadius: '8px',
    background: active ? color + '15' : '#fff',
    color: active ? color : '#5f6368',
    fontWeight: active ? '600' : '400',
    fontSize: '13px',
    cursor: 'pointer',
    transition: 'all 0.15s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
  }),
  actions: {
    display: 'flex',
    gap: '10px',
    paddingTop: '4px',
  },
  btnPrimary: {
    flex: 1,
    padding: '10px 20px',
    background: '#1a73e8',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    fontWeight: '600',
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'background 0.15s',
  },
  btnSecondary: {
    padding: '10px
